#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websrvs.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbpoltekpos")]
	public partial class PembelianDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttrs_pembelian(trs_pembelian instance);
    partial void Updatetrs_pembelian(trs_pembelian instance);
    partial void Deletetrs_pembelian(trs_pembelian instance);
    #endregion
		
		public PembelianDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbpoltekposConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PembelianDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PembelianDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PembelianDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PembelianDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<trs_pembelian> trs_pembelians
		{
			get
			{
				return this.GetTable<trs_pembelian>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trs_pembelian")]
	public partial class trs_pembelian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nofaktur;
		
		private string _vendor;
		
		private string _kode_barang;
		
		private string _nama_barang;
		
		private System.Nullable<int> _jml;
		
		private System.Nullable<int> _hargasatuan;
		
		private System.Nullable<int> _subtotal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnofakturChanging(int value);
    partial void OnnofakturChanged();
    partial void OnvendorChanging(string value);
    partial void OnvendorChanged();
    partial void Onkode_barangChanging(string value);
    partial void Onkode_barangChanged();
    partial void Onnama_barangChanging(string value);
    partial void Onnama_barangChanged();
    partial void OnjmlChanging(System.Nullable<int> value);
    partial void OnjmlChanged();
    partial void OnhargasatuanChanging(System.Nullable<int> value);
    partial void OnhargasatuanChanged();
    partial void OnsubtotalChanging(System.Nullable<int> value);
    partial void OnsubtotalChanged();
    #endregion
		
		public trs_pembelian()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nofaktur", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nofaktur
		{
			get
			{
				return this._nofaktur;
			}
			set
			{
				if ((this._nofaktur != value))
				{
					this.OnnofakturChanging(value);
					this.SendPropertyChanging();
					this._nofaktur = value;
					this.SendPropertyChanged("nofaktur");
					this.OnnofakturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor", DbType="VarChar(50)")]
		public string vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				if ((this._vendor != value))
				{
					this.OnvendorChanging(value);
					this.SendPropertyChanging();
					this._vendor = value;
					this.SendPropertyChanged("vendor");
					this.OnvendorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kode_barang", DbType="VarChar(50)")]
		public string kode_barang
		{
			get
			{
				return this._kode_barang;
			}
			set
			{
				if ((this._kode_barang != value))
				{
					this.Onkode_barangChanging(value);
					this.SendPropertyChanging();
					this._kode_barang = value;
					this.SendPropertyChanged("kode_barang");
					this.Onkode_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_barang", DbType="VarChar(50)")]
		public string nama_barang
		{
			get
			{
				return this._nama_barang;
			}
			set
			{
				if ((this._nama_barang != value))
				{
					this.Onnama_barangChanging(value);
					this.SendPropertyChanging();
					this._nama_barang = value;
					this.SendPropertyChanged("nama_barang");
					this.Onnama_barangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jml", DbType="Int")]
		public System.Nullable<int> jml
		{
			get
			{
				return this._jml;
			}
			set
			{
				if ((this._jml != value))
				{
					this.OnjmlChanging(value);
					this.SendPropertyChanging();
					this._jml = value;
					this.SendPropertyChanged("jml");
					this.OnjmlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hargasatuan", DbType="Int")]
		public System.Nullable<int> hargasatuan
		{
			get
			{
				return this._hargasatuan;
			}
			set
			{
				if ((this._hargasatuan != value))
				{
					this.OnhargasatuanChanging(value);
					this.SendPropertyChanging();
					this._hargasatuan = value;
					this.SendPropertyChanged("hargasatuan");
					this.OnhargasatuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="Int")]
		public System.Nullable<int> subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
